CLASS zcl_travel_rules_std27 DEFINITION
  PUBLIC
  INHERITING FROM zcl_travel_rules27
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_travel_rules_std27 IMPLEMENTATION.
ENDCLASS.
